### PR TITLE
Add benchmark

### PR DESCRIPTION
**Pull request by anvayg**
Creating pull request with an added benchmark for testing integration checks. Currently using one of the benchmarks I had previously written. It's in a new folder called imperative; let me know if you want things organized differently. I think most of the benchmarks in the 'basic' folder (which are currently in the old format) can go to the 'imperative' folder eventually.

As an aside, I had to give myself executable permissions for the latest release of the parser. Not really an issue, but I didn't have to do that earlier.

### CODE REVIEW

**Comment by kjcjohnson** [comment]
> Not really an issue, but I didn't have to do that earlier.

This is interesting. I'll look into it - probably something to do with the new CI setup.

Also, I wasn't aware of this:
image
I think we can just turn this off on this repository.

**Review by kjcjohnson — APPROVED** [review]
Looks good to me!

**Comment by kjcjohnson** [comment]
@anvayg - are you able to merge this yourself, or do you need me to press the button? Not sure what you see.

**Comment by anvayg** [comment]
I don't have write access, so I don't think I can merge myself.

**Comment by kjcjohnson** [comment]
I'll give you write access eventually, but this is a good test 😁

**Pull request merged**
